name: AutoDeployGihubPage

on:
  push:
    branches: [ workflows/AutoDeployGihubPage ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
    - run: |
          echo "NEXT_PUBLIC_REPO=${{ github.repository }}" > .env
          npm install
          npm run export
          touch ./out/.nojekyll
          git config --global user.email "github@example.com"
          git config --global user.name "git workflows"
          git add out/ -f
          git commit -m "Deploy gh-pages"          
          #git subtree push --prefix out origin gh-pages
          git subtree split --prefix out -b gh-pages
          git push -f origin gh-pages:gh-pages
          git branch -D gh-pages